### PR TITLE
Some documentation and improvements for feature flags 

### PR DESCRIPTION
**Pull request by psychon**
@eduardosm Could you take a look at this? Specifically, do you think I got the features for `docs.rs` right?

### CODE REVIEW

**Comment by dalcde** [comment]
I think it would be helpful to provide an explicit list of all feature flags in the documentation. Unless I am missing something, currently the only way to know what the feature flags are is to look into `Cargo.toml` in the source.

**Comment by eduardosm** [comment]
> I think it would be helpful to provide an explicit list of all feature flags in the documentation.

I agree with it. I would write something like:

> This crate has the following feature flags:
>
> - `vendor-xcb-proto` (enabled by default): ....
> - `allow-unsafe-code` (enabled by default): ....
>
> Additionally, in order to reduce the amount of compiled code, only the core X11 protocol and extensions that are needed internally are enabled by default. The following feature flags can be used to enable additional X11 extensions: `composite`, `damage`, `dpms` .......
>
> If you want to take the "I do not want to think about this"-approach, you can enable the `all-extensions` feature to just enable, well, all extensions.

**Comment by psychon** [comment]
Updated.

**Comment by eduardosm** [comment]
Looks good to me :+1:

**Pull request merged**
