### PR TITLE
Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by eduardosm**
Fixes https://github.com/psychon/x11rb/issues/323.

### CODE REVIEW

**Comment by eduardosm** [comment]
I'm not sure if I've got mergify right. And maybe you need to configure something to disable Travis.

**Comment by psychon** [comment]
We will definitely have to clean up that git history. :-D Can you do that? Feel free to just squash it all or just squash my commits.
Random thought: Is it worth it to keep Travis for now to be able to compare results? I would say "yes". I'd then do a couple of "experimentation PRs" that should fail and thus test things. (Or better: just a single PR for that)

> I'm not sure if I've got mergify right. 

You didn't, but I do not know what would be the right thing. There is a "check [this] config against pr 1234" feature on their webpage. It says that the new rule does not match this PR. I guess that means "no regex", which does make some sense to me.
Hm... but they do mention regex in their docs.... but https://docs.mergify.io/conditions.html#github-actions also sounds related

Some experiments say this matches:
```
- status-success=big-endian-test
- status-success=build (stable)
- status-success~=build (.*)
```
However... I am not quite sure what happens when some of the jobs fail and others not... perhaps the regex says "there is some successful status"? If so, we would need negation

Another random doc pointer: https://docs.mergify.io/conditions.html#validating-all-status-check
```
Do not use conditions such as:

#check-failure=0, because this will be true as soon as the pull request is created and before any service report its status (see point 2. above).

check-success~=build while expecting this to wait for all status checks that have build in their name (see point 1. above).

Such conditions won’t do what you want them to do.
```

For future me: I can test a new config at https://dashboard.mergify.io/github/psychon/config-editor?repositoryName=x11rb&pullRequestNumber=533

**Comment by psychon** [comment]
I also just removed Travis and added some of these new checks from the list of required status checks on the branch protection page. That does not seem to do something here, but might already work for future PRs.

**Comment by eduardosm** [comment]
> We will definitely have to clean up that git history. :-D Can you do that?

Seems a good idea, I'll do it.

**Comment by eduardosm** [comment]
Much better :)

**Comment by eduardosm** [comment]
> Random thought: Is it worth it to keep Travis for now to be able to compare results? I would say "yes". I'd then do a couple of "experimentation PRs" that should fail and thus test things. (Or better: just a single PR for that)

I believe that it won't hurt to keep it as long as it doesn't constrain the global check result.

**Comment by psychon** [comment]
Well, okay... goodbye, Travis. Next up is getting mergify to work again, I guess.

Thanks for preparing this.

**Pull request merged**
