### PR TITLE
Revert adding raw-window-handle

### PR DESCRIPTION
**Pull request by notgull**
The MSRV bump is causing issues, unfortunately.

Not released yet, so not a breaking change.

### CODE REVIEW

**Review by psychon — APPROVED** [review]

**Comment by kchibisov** [comment]
But you can force 0.5.0 or test minimal deps? Because 0.5.0 is 1.60, however 0.5.1 is 1.64.

**Comment by psychon** [comment]
Well... how can I do that? `--minimal-versions` is unstable and hence not available in 1.56.

This is the relevant GitHub workflow that started failing:
https://github.com/psychon/x11rb/blob/a345be8ed50eb562952294a9fa8127c7755e6448/.github/workflows/CI.yml#L180-L198

**Comment by kchibisov** [comment]
Yeah, I guess for now only if you use the `Cargo.lock`.

We bumped MSRV to 1.64, because that's what used by most graphics stuff right now anyway (and it was required to have zero dependencies).

**Comment by psychon** [comment]
I am reverting the revert in #935

**Pull request merged**
