### PR TITLE
Add a function for getting the name of a request

### PR DESCRIPTION
**Pull request by psychon**
Signed-off-by: Uli Schlachter <psychon@znc.in>

---

This is how far I got before noticing that #314 does not really work. Dunno if this should be merged or not.

- [ ] TODO: It just occurred to me that this should use the generated constants instead of having just the plain number

### CODE REVIEW

**Comment by eduardosm** [comment]
whoops, I mistakenly checked the TODO checkbox (and then unchecked it again), just in case you get some notification about me modifying this PR

**Comment by psychon** [comment]
Nope, no notifications. :-)

**Comment by eduardosm** [comment]
Can this be closed?

**Comment by psychon** [comment]
Dunno. I still feel like this could be useful, but so far have not come across a case where I would be able to use this information. If #314 is not possible... well, I guess then this should be closed. Do you agree that #314 is not possible and that the addition in this PR is not useful?

**Comment by eduardosm** [comment]
If #314 is not possible, I cannot think of any other use of this right now. Anyways, this is right now written for the old python generator, so if someday we want this, it would need to be done from scratch.

**Pull request closed without merging**
