### PR TITLE
Introduce ParseError::InsufficientDataError.

### PR DESCRIPTION
**Pull request by khuey**
As we discussed. I don't claim to have gotten every single case but I do believe I got all the big ones.

### CODE REVIEW

**Comment by eduardosm** [comment]
I think that `ParseError::InsufficientData` would be a better name (without the `Error` suffix). Otherwise, :+1:

**Comment by psychon** [comment]
Yay. It's always great when items from my todo list disappear because someone sends a PR.

I agree with @eduardosm about the naming.

For the plan after this PR, I propose to add another variant to `ParseError`. Perhaps called `InvalidValue`? Would it make sense to make this `InvalidValue(i64, &'static str)` so that the error can e.g. represent `The value 42 is not valid for "Whatever"`?

Anyway, afterwards the code should be converted to these two new variants. Once nothing uses `ParseError` any more, it can be removed. This also makes sure that no piece of code is forgotten.

**Comment by khuey** [comment]
Hmm, it doesn't seem like CI is running again on the new changeset.

**Comment by psychon** [comment]
At first I thought this "close, then open" did not do anything. But on https://travis-ci.org/github/psychon/x11rb/pull_requests I see the build as pending: https://travis-ci.org/github/psychon/x11rb/builds/700101374

Perhaps Travis only reports to GitHub once it actually starts building? Dunno...

**Comment by psychon** [comment]
CI succeeded, but no one told GitHub about it. Sigh.

**Pull request merged**
