### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by eduardosm**

### CODE REVIEW

**Comment by psychon** [comment]
I guess "nix broke" is a good reason to bump the MSRV. :-(

**Comment by eduardosm** [comment]
> I guess "nix broke" is a good reason to bump the MSRV. :-(

As you prefer, I was about to rollback to 0.20 and list it in https://github.com/psychon/x11rb/issues/538.

**Comment by psychon** [comment]
Feel free to bump to 1.41. Seems like that also means "newer smol" (thanks for the link; I totally forgot about #538)

**Comment by eduardosm** [comment]
It looks like it is not going to be that easy, some dependencies of the newer smol (async-lock and socket2) have further bumped their MSRV and do not build with 1.41 anymore.

**Review by psychon — APPROVED** [review]

**Comment by psychon** [comment]
I updated the branch protection rule: Removed `build (1.40.0)` and added `build (1.41.1)`, but apparently that does not apply to this PR...?

However, that reminds me: You also need to update `.mergify.yml` for the new name of the check.

**Comment by eduardosm** [comment]
> However, that reminds me: You also need to update `.mergify.yml` for the new name of the check.

I did update it

**Comment by psychon** [comment]
Oh, sorry.

**Pull request merged**
