### PR TITLE
xcbgen: Remove useless conversions

### PR DESCRIPTION
**Pull request by eduardosm**
Fixes https://github.com/psychon/x11rb/issues/461

### CODE REVIEW

**Comment by eduardosm** [comment]
https://travis-ci.org/github/psychon/x11rb/jobs/694590135#L373-L393
There's an explicit `allow` there, that's a bug in clippy for sure

**Comment by eduardosm** [comment]
> https://travis-ci.org/github/psychon/x11rb/jobs/694590135#L373-L393
> There's an explicit `allow` there, that's a bug in clippy for sure

Reported: https://github.com/rust-lang/rust-clippy/issues/5683

**Comment by eduardosm** [comment]
https://travis-ci.org/github/psychon/x11rb/jobs/694597583#L370-L377
huh?

**Comment by psychon** [comment]
> huh? I cannot reproduce this locally...

Are you trying with Rust 1.43?

https://github.com/rust-lang/rust-clippy/commit/e55b920970fdc33f5ddaf7757738fbacdadf15ab

**Comment by eduardosm** [comment]
> Are you trying with Rust 1.43?

I was trying with 1.43.0. I updated to 1.43.1 and now the warning appears.

> Edit: Renaming a lint may be one of the most annoying kinds of churn. Is it worth complaining about this upstream? Perhaps we should only run clippy on `stable` and `nightly` (because `nightly` is allowed to fail, so we might still get "advance warning" on upcoming changes).

That's likely the best idea, keeping different versions of clippy happy is a pita.

**Pull request merged**
