### PR TITLE
Update tutorial example8

### PR DESCRIPTION
**Pull request by w3bdev1**
Requested 4 events but handled/needed only 2 of them in event loop.

### CODE REVIEW

**Comment by psychon** [comment]
Thanks for the PR. As written here, this code more or less comes from "elsewhere" and I am not sure whether we really want to change things too much from that base https://github.com/psychon/x11rb/blob/8344ed494d1953c01e66f3d81df5e0dbe24ef804/x11rb/examples/tutorial.rs#L3-L6

Also, requesting button events has side effects (the events are no bubbled up to the parent window), but I guess this doesn't really matter.

Hm... any other opinions? Should we merge this or not? I am fine with either, but have a hard time deciding.

**Comment by notgull** [comment]
I'm leaning towards no. If it's supposed to be a port of the libxcb code, we shouldn't change the masks. If necessary we could probably raise the issue with libxcb to see if this was intended.

**Comment by w3bdev1** [comment]
I don't think it is a deviation from the original libxcb code. Moreover it is less confusing from a reader's perspective.

Although as @notgull mentioned, similar issue need to be raised with libxcb as well.

**Review by psychon — APPROVED** [review]
I "ported" this PR to libxcb: https://gitlab.freedesktop.org/xorg/lib/libxcb/-/merge_requests/36

**Pull request merged**
